### ISSUE TITLE
 add version 5.05

### ISSUE THREAD

**Issue by TestkitDev** [PokersKun/PPPwn-Loader#1]
Hi possible to add version 5.05 I would like to test two payloads on my test kit with IPwnder_v1.1

**Comment by PokersKun** [comment]
> Hi possible to add version 5.05 I would like to test two payloads on my test kit with IPwnder_v1.1

Unfortunately this is just a front-end GUI tool for PPPwn, and if PPPwn doesn't support it then it won't be supported.

**Comment by TestkitDev** [comment]
OK, no problem
