### ISSUE TITLE
Suggestion!!

### ISSUE THREAD

**Issue by faroukbmiled** [PokersKun/PPPwn-Loader#2]
Instead of using the python frozen exe of the PPPwn script ,can you use the c++ rewrite by [xfangfang](https://github.com/xfangfang)
It'd be much better (https://github.com/xfangfang/PPPwn_cpp?tab=readme-ov-file)

**Comment by PokersKun** [comment]
Good suggestion, last time I was checking out this C++ rewrite it hadn't completed the functionality behind stage2, if it had I could have tried replacing it with the Python version recently.

**Comment by PokersKun** [comment]
It's ready for you to try.
https://github.com/PokersKun/PPPwn-Loader/releases

**Comment by faroukbmiled** [comment]
Thank you so much ,great job!
