### ISSUE TITLE
payload sent faliure

### ISSUE THREAD

**Issue by JetpropelledSnake** [PokersKun/PPPwn-Loader#5]
Hello bro,
Nice job for the rewrite cpp, fast and terrific!
It came to 4th stage and was ready to send payload.
During waiting(40 seconds maybe), the below log came out, it said "done".
However, no pawn and goldhen pop out in ps4.
pls help check, tks.

2024/05/17 19:40:23 - [*] Sending IPCP configure ACK...
2024/05/17 19:40:23 - [+] STAGE 4: Arbitrary payload execution
2024/05/17 19:40:23 - [*] Sending stage2 payload...
2024/05/17 19:40:56 - [ERROR: /home/pokers/work/PPPwn_cpp/build/_deps/pcapplusplus-src/Pcap++/src/PcapLiveDevice.cpp: sendPacket:628] Error sending packet: send error: PacketSendPacket failed: 连到系统上的设备没有发挥作用。  (31)
2024/05/17 19:41:12 - [ERROR: /home/pokers/work/PPPwn_cpp/build/_deps/pcapplusplus-src/Pcap++/src/PcapLiveDevice.cpp: sendPacket:628] Error sending packet: send error: PacketSendPacket failed: 连到系统上的设备没有发挥作用。  (31)
2024/05/17 19:41:33 - [ERROR: /home/pokers/work/PPPwn_cpp/build/_deps/pcapplusplus-src/Pcap++/src/PcapLiveDevice.cpp: sendPacket:628] Error sending packet: send error: PacketSendPacket failed: 连到系统上的设备没有发挥作用。  (31)
2024/05/17 19:41:33 - [+] Done!

**Comment by JetpropelledSnake** [comment]
win11 -- ps4 pro 7209b -- nmap v1.76 installed

**Comment by PokersKun** [comment]
It looks like a Pcap related error is being encountered in the final stage, can you update PPPwnCPP to the latest version in Settings or use the [latest release](https://github.com/PokersKun/PPPwn-Loader/releases/latest) to verify if that solves your problem?

**Comment by JetpropelledSnake** [comment]
got same  Pcap related error, maybe it's hardware imcompatiable like many others, awaiting Andy's furure update....
