### ISSUE TITLE
pc和ps4是某一交换机下的两个子设备，pc不能通过pppwn实现ps4越狱

### ISSUE THREAD

**Issue by applekiller7** [PokersKun/PPPwn-Loader#7]
是否预计添加一个新的特性，以支持在同一子网下实现9.03及以上的系统固件的ps4越狱？

**Comment by PokersKun** [comment]
这个估计得看 [PPPwn_cpp](https://github.com/xfangfang/PPPwn_cpp) 能不能优化 Pcap 传输的问题了

**Comment by applekiller7** [comment]
issue重定向
